# Generated by Django 6.0.3 on 2026-03-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('admin', 'Admin'), ('other', 'Other')], max_length=20)),
                ('department', models.CharField(max_length=50)),
                ('on_duty', models.BooleanField(default=True)),
            ],
        ),
    ]
